// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	DB: D1Database;
}

interface D1Database {
	binding: string;
	database_name: string;
	database_id: string;
}
